title: 'b2a3e8.github.io'
description: "A draft blog."
baseurl: ""
url: "https://spazznolo.github.io"
google_analytics: UA-177238175-1

header_pages:
  - home.md
  - background.md
  - goalies.md
  - tennis.md
  - draft.md
  - post-regulation.md
  
style: dark

footer: ""

# Build settings
markdown: kramdown
remote_theme: spazznolo/jekyll-theme-console
